title: <p>    <br></p>
logo: /assets/logo.png
description: <div class="e"><font color="#a9cba3", font size="4.7"><b><i>Welcome to my homepage! </i></b></font></div><br><b><i><font size="4">YI-PEI CHAN</font> is an actuary specializes in life insurance. She earned her Bachelor's Degree in Economics and Biological Statistics Program from National Taiwan University. She is enthusiastic about math, programming, entrepreneurship and civic engagement.</i></b> 
show_downloads: false
google_analytics: UA-123794012-1
theme: jekyll-theme-minimal

